export const metadata = [
  {
    slug: "jays-transport",
    title: "jay's transport",
    description: "Generated by jay's transport",
  },
  {
    slug: "mototaxi",
    title: "mototaxi",
    description: "jay's transport mototaxi",
  },
];
