export const metadata = [
  {
    slug: "jays-transport",
    title: "jay's transport",
    description: "Generated by jay's transport",
  },
  {
    slug: "mototaxi",
    title: "mototaxi",
    description: "jay's transport mototaxi",
  },
  {
    slug: "vtc",
    title: "vtc",
    description: "jay's transport vtc",
  },
  {
    slug: "van",
    title: "van",
    description: "jay's transport van",
  },
];