"use client";

import Metadata from "@/app/components/metaData/metaData";
import './home.css';
import MotoServices from "@/app/components/services/page";

export default function HomePage() {
  return (
    <div className="flex bg-white flex-col items-center w-full">
      <Metadata
        title={"Jay's transport"}
        description={"Generated by Jay's transport"}
      />
      <div className="banner-container">
        <img className="banner-img" alt="banner" src="/img/banner.png" />
        <div className="banner-text">
          <p>où aimerais-tu aller</p>
          <h1>une nouvelle classe de service</h1>
        </div>
      </div>
      <div className="home-content">
        <h1>Jay’s Transport est le leader des services de chauffeurs privés VTC et de
          Taxi moto à Paris et en Île-de-France.</h1>
        <p>Nous vous offrons une gamme complète de services et un transport d'une
          qualité irréprochable. En tant que leaders du transport avec chauffeur
          privé dans l'Essonne (91), nous avons noué des partenariats avec des
          chauffeurs de la région parisienne afin d'élargir notre offre, comprenant
          des trajets en berline, en van et en moto-taxi.</p>
      </div>
      <h1 className="vehicle-heading">Notre parc de véhicules</h1>
      <div className="vehicle-container">
        <div className="vehicle">
        <img src="/img/bike.jpg" alt="bike"/>
        <p>TAXI MOTO</p>
        </div>
        <div className="vehicle">
        <img src="/img/berline.png" alt="berline"/>
        <p>BERLINE OU SUV</p>
        </div>
        <div className="vehicle">
        <img src="/img/van.png" alt="van"/>
        <p>VAN ( 9 PLACES )</p>
        </div>
      </div>
      <h1 className="vehicle-heading">Nos services VTC-TAXI avec chauffeur privé et taxi moto</h1>
      <MotoServices />
      </div>
  );
}
