"use client";

import Metadata from "@/app/components/metaData/metaData";
import './home.css';
import OurServices from "@/app/components/services/page";
import { useTranslation } from "react-i18next";
import { ContactForm } from "@/app/components/Contact/page";

export default function HomePage() {
  const { t } = useTranslation();
  return (
    <div className="flex bg-white flex-col items-center w-full">
      <Metadata
        title={"Jay's transport"}
        description={"Generated by Jay's transport"}
      />
      <div className="banner-container">
        <div className="banner-text">
          <p>{t('whereToGo')}</p>
          <h1>{t('serviceClass')}</h1>
        </div>
      </div>
      <div className="home-content">
        <h1>{t('introDescription')}{t('fullRangeDescription')}</h1>
      </div>
      <div className="single-frame">
      <h1 className="vehicle-heading">{t('fleet')}</h1>
      <div className="vehicle-container">
        <div className="vehicle">
        <img src="/img/bike_new.png" alt="bike"/>
        <p>{t('motoTaxi')}</p>
        </div>
        <div className="vehicle">
        <img src="/img/car_new.png" alt="berline"/>
        <p>{t('sedanSUVHome')}</p>
        </div>
        <div className="vehicle">
        <img src="/img/van.png" alt="van"/>
        <p>{t('van')}</p>
        </div>
      </div>
      </div>
      <h1 className="vehicle-heading">{t('vtcTaxiServices')}</h1>
      <OurServices />
      <h1 id="contact" className="vehicle-heading" style={{ paddingTop: '100px' }}>{t('contact')}</h1>
      <ContactForm />
      </div>
  );
}
